prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix boamp: <https://data.maudry.com/voc/boamp#>

#La liste des différentes classes d'acheteur

select distinct ?classe where {

  ?marche boamp:acheteur ?acheteur .
  ?acheteur rdfs:type ?classe .

  } limit 50 offset 0&reasoning=false
