prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix boamp: <https://data.maudry.com/voc/boamp#>

# La liste des titulaires de marchés d'origine espagnole

select distinct ?objet where {

?objet a boamp:Titulaire ;
         boamp:pays "ES" .

}
